language: go

sudo: false

os:
  - linux
  - osx

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6beta1

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/btcsuite/btcd
  - go get github.com/btcsuite/btcwallet
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - $HOME/gopath/bin/goveralls -ignore="**/*.pb.go" -service=travis-ci -v ./...
